import { defineCollection, z } from 'astro:content';
import { glob, file } from 'astro/loaders';

const localeEnum = z.enum(['en', 'es', 'pt']);
const localized = z.object({ en: z.string(), es: z.string(), pt: z.string() });

/** Team members — src/content/team.json (array). Avatars are imported masters in src/assets/team/. */
const team = defineCollection({
  loader: file('src/content/team.json'),
  schema: ({ image }) =>
    z.object({
      id: z.string(),
      name: z.string(),
      nickname: z.string().optional(),
      surnameTbd: z.boolean().default(false),
      role: localized,
      bio: localized,
      bioStatus: z.enum(['confirmed', 'to-confirm']).default('to-confirm'),
      avatar: image(),
      focal: z.object({ x: z.number().min(0).max(1), y: z.number().min(0).max(1) }).default({ x: 0.5, y: 0.4 }),
      accent: z.string().regex(/^#[0-9a-f]{6}$/i).optional(),
      links: z
        .object({ linkedin: z.url(), instagram: z.url(), artstation: z.url(), website: z.url() })
        .partial()
        .optional(),
      order: z.number(),
      active: z.boolean().default(true),
    }),
});

/** News / devlog — src/content/news/{en,es,pt}/<slug>.md ; entries in other languages share `translationOf`. */
const news = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/news' }),
  schema: ({ image }) =>
    z.object({
      title: z.string().max(90),
      date: z.coerce.date(),
      updated: z.coerce.date().optional(),
      lang: localeEnum,
      translationOf: z.string(),
      cover: image().optional(),
      coverAlt: z.string().optional(),
      excerpt: z.string().max(200),
      tags: z.array(z.enum(['mindaro', 'studio', 'events', 'devlog', 'press'])).default([]),
      author: z.string().optional(),
      draft: z.boolean().default(false),
      needsReview: z.boolean().default(false),
    }),
});

/** Open roles — src/content/jobs/{en,es,pt}/<slug>.md */
const jobs = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/jobs' }),
  schema: z.object({
    title: z.string(),
    lang: localeEnum,
    translationOf: z.string(),
    department: z.enum(['art', 'engineering', 'audio', 'design', 'production', 'marketing', 'other']),
    engagement: z.enum(['tbd', 'collaboration', 'contract', 'part-time', 'full-time']).default('tbd'),
    location: z.string().default('remote'),
    open: z.boolean().default(true),
    example: z.boolean().default(false),
    order: z.number().default(0),
    applySubject: z.string(),
  }),
});

/** Press assets — generated by scripts/import-assets.mjs into src/data/press-assets.json */
const pressAssets = defineCollection({
  loader: file('src/data/press-assets.json'),
  schema: z.object({
    id: z.string(),
    group: z.enum(['bundle', 'logos', 'mindaro-logos', 'key-art', 'screenshots', 'concept-art', 'characters', 'team', 'docs', 'video']),
    title: localized,
    description: localized.optional(),
    href: z.string(),
    bytes: z.number(),
    dims: z.string().optional(),
    preview: z.string().optional(),
    order: z.number(),
  }),
});

export const collections = { team, news, jobs, pressAssets };
